### ISSUE TITLE
SOLID principes in Javascript

### ISSUE THREAD

**Issue by jojube95** [jojube95/eventos#156]

**Comment by jojube95** [comment]
bc9b9e5cb2594ae2a492f3355245ad756d367cae

**Comment by jojube95** [comment]
90cff0be6f4c6bb16f2c03e0272f5793cccae496

**Comment by jojube95** [comment]
830fb4f7bff3ac73db5317e7d7a4ad77f1370128

**Comment by PRO-BROS** [comment]
I also faced a similar issue on my [site](https://prhocoding.com/) but thankfully I hire a developer which resolve that's issue.

**Comment by jojube95** [comment]
b3213c3c7b4b07683d637f6618a1e93bbb53cff5

**Comment by jojube95** [comment]
dd600fe5ed763e29db322cb7f644923188ef8ec4

**Comment by jojube95** [comment]
dc5db2487ec9b28d65a93aad93ae489e536d847c

**Comment by jojube95** [comment]
1dc9a95bfb2fec25cd53d00704be7df4ec746b59

**Comment by jojube95** [comment]
df649397a68857c949527bbef9ccb4ec50048f5f
